app:
  baseUrl: https://backstage.foundations-software-engineering.com

backend:
  baseUrl: https://backstage.foundations-software-engineering.com
  cors:
    origin: https://backstage.foundations-software-engineering.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${PROD_GITHUB_CLIENT_ID}
        clientSecret: ${PROD_GITHUB_CLIENT_SECRET}
