app:
  baseUrl: https://backstage-deployment-1006240973223.europe-west10.run.app

backend:
  baseUrl: https://backstage-deployment-1006240973223.europe-west10.run.app
  cors:
    origin: https://backstage-deployment-1006240973223.europe-west10.run.app
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${PROD_GITHUB_CLIENT_ID}
        clientSecret: ${PROD_GITHUB_CLIENT_SECRET}
