# Only difference here is that we need a caFile if it is deployed inside of a kube cluster
kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: ${K8S_URL}
          name: "k8s"
          authProvider: serviceAccount
          skipTLSVerify: false
          skipMetricsLookup: true
          serviceAccountToken: ${K8S_ACCOUNT_TOKEN}
          caData: ${K8S_CA_DATA}
          caFile: ${K8S_CA_FILE}
