app:
  baseUrl: https://backstage-deployment-1006240973223.europe-west10.run.app

backend:
  baseUrl: https://backstage-deployment-1006240973223.europe-west10.run.app
  cors:
    origin: https://backstage-deployment-1006240973223.europe-west10.run.app
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    plugin:
      auth:
        connection: 
          database: ${POSTGRES_DB}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${PROD_GITHUB_CLIENT_ID}
        clientSecret: ${PROD_GITHUB_CLIENT_SECRET}
