site_name: CODE-IDP Platform
site_description: This is the user guide for the CODE-IDP platform.
docs_dir: docs
nav:
  - Overview:
      - Introduction: 'index.md'
  - Components:
  - CHANGELOG: 'CHANGELOG.md'

plugins:
  - techdocs-core
  - include-markdown
