
name: Create User DB
on:
  push:
    branches:
      - feat/cloudsql-gh-action
  workflow_dispatch:


jobs:
  create-db:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        name: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - id: 'Set_up_Cloud_SDK'
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
