
name: Create User DB test
on:
  push:
    branches:
      - main # remove this line later
  workflow_dispatch:


jobs:
  create-db:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "Hello World"
