name: Build and Publish TechDocs to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    
    env: 
        TECHDOCS_BUCKET_NAME: ${{ secrets.TECHDOCS_BUCKET_NAME }}
        TECHDOCS_GCS_CREDENTIALS: ${{ secrets.TECHDOCS_GCS_CREDENTIALS }}
        ENTITY_NAMESPACE: 'default'
        ENTITY_KIND: 'Component'
        ENTITY_NAME: 'code-idp-docs'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@4.4.1 --activate
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.9'

      - name: Install techdocs-cli
        run: yarn global add @techdocs/cli

      - name: Install mkdocs and mkdocs-plugin
        run: python3 -m pip install mkdocs-techdocs-core==1.*
    
      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type googleGcs --storage-name $TECHDOCS_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
