name: Build and Publish TechDocs to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    
    env: 
        ENTITY_NAMESPACE: 'default'
        ENTITY_KIND: 'Component'
        ENTITY_NAME: 'code-idp-docs'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type googleGcs --storage-name $TECHDOCS_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
