apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: MennaTullahTaha/gke_with_terraform # Repo we're grabbing the gke terraform config from.
  description: $ {{ values.name }} running on GKE cluster managed by Terraform.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
